CREATE DATABASE ISTA;

USE ISTA;

CREATE TABLE stagiaires (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    nom VARCHAR(50) NOT NULL,
    prenom VARCHAR(50) NOT NULL,
    filiere VARCHAR(50) NOT NULL,
    annee_etude DATE NOT NULL,
    type_bac VARCHAR(50) NOT NULL,
    annee_bac DATE NOT NULL
);
