const arr = [
    "Technologie des aliments",
    "Technicien spécialisé en oléoculture et oléotechnie",
    "Management agricole",
    "Stylisme modelisme industriel",
    "Techniques d'habillement industrialisation",
    "Haute couture",
    "Technico - Commercial en Vente de Véhicules et Pièces de Rechange",
    "Exploitatio",
    "Gestion des entreprises",
    "Management hôtelier",
    "Technicien Spécialisé Bureau d'Etude en Construction Métallique",
    "Développement Digital",
    "Educateur Spécialisé dans la Petite Enfance",
    "Infographie",
    "Management Touristique",
    "Automatisation et Instrumentation Industrielle",
    "Gestion des Entreprises",
    "Génie Civil",
    "Technicien Spécialisé en oléiculture et Oléotechnie",
    "Technologie des Aliments",
    "Maintenance des Machines et Outillage en Plasturgie",
    "Chimie Cuir",
    "Bureau d'Etude en Construction Métallique",
    "Technicien Spécialisé en Contrôle Qualité Textile",
    "Management et Méthodes Cuir",
    "Educateur spécialisé dans la petite enfance",
    "Management touristique",
    "Management Hôtelier",
    "Agriculture de Précision",
    "Géomètre Topographe",
    "Infographie prépresse",
    "Management Agricole",
    "Qualité Hygiène Sécurité Environnement",
    "Techniques agricoles",
    "Transformation et valorisation des plantes Aromatiques et médicinales",
    "Exploitation",
    "Infrastructure Digitale",
    "Technicien Spécialisé en Emballage et Conditionnement",
    "Gestion des entreprise",
    "Infrastrecture Digitale",
    "Management Agricol",
    "Emballage et conditionnement"
]

arr.forEach(a => {
    const v = a.trim().toUpperCase().split(' ').map(e => e[0]).join('')
    console.log(v)
});
